services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    #restart: always
    depends_on:
      - api

  api:
    build:
      context: api
    ports:
      - "1234:1234"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    expose: 
      - 1234
    #restart: always
