services:
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    build:
      context: api
    ports:
      - "1234:1234"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
